In [1]:
import xarray as xr
import seaborn as sns
import numpy
import pandas

In [2]:
bw_only = xr.open_dataset('slimane_1995/bw_only.nc').to_dataframe().reset_index()
ga_and_bw = xr.open_dataset('slimane_1995/ga_and_bw.nc').to_dataframe().reset_index()
ga_only = xr.open_dataset('slimane_1995/ga_only.nc').to_dataframe().reset_index()
random_only = xr.open_dataset('slimane_1995/random_only.nc').to_dataframe().reset_index()

In [ ]:
# bw_only.dims
# bw_only = bw_only.assign_coords({
#     'observation_sequence': numpy.arange(10),
#     'n_states': numpy.arange(2,21),
#     'iteration': numpy.arange(100),
#     'time': numpy.arange(50)
# })s
# bw_only = bw_only.to_dataframe().reset_index()

In [24]:
def reduktions_moped(x):
    print(x)

g = bw_only[bw_only['time'] == 49].groupby(['observation_sequence', 'n_states'])['__xarray_dataarray_variable__'].rolling(5).max()

x = g.groupby('observation_sequence').mean()
x.apply(numpy.exp)

observation_sequence
0    0.291020
1    0.331010
2    0.052927
3    0.288976
4    0.407835
5    0.673009
6    0.074016
7    0.042676
8    0.761373
9    0.004286
Name: __xarray_dataarray_variable__, dtype: float64

In [102]:
def calc_rolling_average(df, n):
    soos = df[df['time'] == 49].groupby(['observation_sequence', 'n_states'])['__xarray_dataarray_variable__'].rolling(n).max()
    return soos.groupby('observation_sequence').mean()

mopeds = [calc_rolling_average(bw_only, i) for i in range(1,6)]


# bw_only.groupby(['observation_sequence', 'n_states'])['__xarray_dataarray_variable__']
df = pandas.DataFrame(mopeds)
df['window_size'] = [i for i in range(1,6)]
# df.drop(columns=['observation_sequence'])
# df.groupby('window_size').plot()
pandas.concat(mopeds, axis=1).apply(numpy.exp)

,__xarray_dataarray_variable__,__xarray_dataarray_variable__,__xarray_dataarray_variable__,__xarray_dataarray_variable__,__xarray_dataarray_variable__
observation_sequence,,,,,
0,0.117670,0.205663,0.250022,0.275707,0.291020
1,0.173914,0.239238,0.279662,0.308685,0.331010
2,0.011285,0.025700,0.037296,0.045893,0.052927
3,0.126225,0.190953,0.231886,0.263905,0.288976
4,0.231232,0.331443,0.373962,0.396218,0.407835
5,0.650008,0.672725,0.673009,0.673009,0.673009
6,0.023575,0.043554,0.056867,0.066395,0.074016
7,0.011496,0.024425,0.032470,0.038212,0.042676
8,0.563508,0.694434,0.734001,0.751305,0.761373
9,0.000334,0.001248,0.002269,0.003294,0.004286

In [101]:
bw_only[bw_only['time']==49].groupby(['observation_sequence'])['__xarray_dataarray_variable__'].mean().apply(numpy.exp)

observation_sequence
0    0.117670
1    0.173914
2    0.011285
3    0.126225
4    0.231232
5    0.650008
6    0.023575
7    0.011496
8    0.563508
9    0.000334
Name: __xarray_dataarray_variable__, dtype: float64

In [26]:
ga_and_bw[ga_and_bw['time']==250].groupby(['observation_sequence'])['__xarray_dataarray_variable__'].mean().apply(numpy.exp)

observation_sequence
0    0.224709
1    0.323321
2    0.005775
3    0.044960
4    0.385529
5    0.672166
6    0.098889
7    0.057881
8    0.723814
9    0.000076
Name: __xarray_dataarray_variable__, dtype: float64

In [15]:
ga_and_bw[ga_and_bw['__xarray_dataarray_variable__'].isna()]

,observation_sequence,n_states,iteration,time,__xarray_dataarray_variable__
176919,0,7,4,215,NaN
176920,0,7,4,216,NaN
176921,0,7,4,217,NaN
176922,0,7,4,218,NaN
176923,0,7,4,219,NaN
...,...,...,...,...,...
4768995,9,18,99,246,NaN
4768996,9,18,99,247,NaN
4768997,9,18,99,248,NaN
4768998,9,18,99,249,NaN
4768999,9,18,99,250,NaN

In [ ]:
shish = bw_only.stack(moped=['observation_sequence', 'n_states', 'variable'])
grupps = shish.groupby('moped')

def shishalavisha(x, axis):
    print(x.shape)
    print('sheesh')

for label, schmoos in grupps:
    r = schmoos.coarsen(iteration=3, boundary="trim")
    # r = schmoos.rolling(iteration=3, min_periods=3)

    # c = r.construct(iteration=['shish', 'swish'])
    r.reduce(shishalavisha, keep_dims=False)
    # break
    # print(r)
    # c.reduce(shishalavisha, dim=['shish', 'swish'])
    break
    # break
    for x in c:
        # print(x)
        print(x)
        break

    break

In [ ]:
schrolling = bw_only.isel(iteration=slice(0,99)).coarsen(iteration=3)

def schmoped(x, axis):
    print(x.argmin())
    # print(axis)
    print(x.shape)


# schrolling.reduce(schmoped)
schmonstrugd = schrolling.construct(iteration=['bins', 'reduce'])
schmonstrugd
# indies = schmonstrugd.isel(time=-1).argmax('reduce')

r = bw_only.isel(iteration=slice(0,99)).rolling(iteration=3, min_periods=3)
# schmonstrugd.isel(reduce=indies)
# indies

bw_only.shape

for label  in schmonstrugd:
    print(label.shape)
    # print(arr_window)
    break
print(bw_only.shape)

In [ ]:
# def get_max_of_n_for_dim(data_array, n):


# x = bw_only.sel(iteration=[0, 1, 5])
# y = bw_only.sel(iteration=[7,8,9]).resample()
# bw_only.sel( < 100).groupby_bins(group='iteration', bins=3)
# moped = bw_only.isel(iteration=slice(0,99))

# grupped_time_only = moped.isel(time=-1)
grupped = bw_only.isel(iteration=slice(0,99)).groupby_bins(group='iteration', bins=33)

shish = []

def moped_reduction(x, axis):
    # return x[shish[0]]
    print(type(x))
    

# grupped.reduce(moped_reduction, dim=['n_states', 'iteration'])


for (label, group) in grupped:
    # print(group)
    times = group.isel(time=-1)
    x  = times.argmax(dim='iteration')
    y = x.expand_dims({'time': 50})
    print(y)
    print(x)
    group.isel(iteration=y)
    # shish.append(tuple(x))
    break

# grupped.reduce(moped_reduction)

# moped.groupby_bins(group='iteration', bins=33).reduce(moped_reduction)


# get only them motherfugging values from time=-1

# 
# 
# 
# 
# 
# moped.expand_dims('shishalavisca')

In [ ]:
x = xr.Dataset(
    {
        "temperature": ("station", 20 * numpy.random.rand(4)),
        "pressure": ("station", 500 * numpy.random.rand(4)),
    },
    coords={"station": ["boston", "nyc", "seattle", "denver"]},
)
x.sel(station='boston')
x.coords

# time
# log_probability

x['temperature']



# pressure for each station
# temperature for each station

# log_probs and time

In [ ]:
data = bw_only.isel(time=-1, n_states=4, observation_sequence=4)
# sns.displot(data)
# sns.displot(data['iteration'])
bw_only.loc[bw_only.n_states]

In [ ]:
ga_only_mean = bw_only / 5
sns.lineplot(ga_only_mean.mean(axis=1).T)

In [ ]:
bw_only_mean[3]